language: python

python:
  - 2.7
  - 3.5

services: postgresql

env:
  - DJANGO=1.10.5

before_install:
  - export DJANGO_SETTINGS_MODULE=travis.settings
  - export PYTHONPATH=$HOME/builds/laboiteproject/laboite-erp
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
- python manage.py migrate --noinput
- python manage.py test --noinput
