language: python

python:
  - 2.7
  - 3.5

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=travis.settings
  - export PYTHONPATH=$HOME/builds/laboiteproject/laboite-erp

install:
  - pip install -e .[postgresql]

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
- python manage.py migrate --noinput
- python manage.py test --noinput
